version: '3.7'

services:

  database:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'testing'
    healthcheck:
      test: ["CMD", "pg_isready -h localhost"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
